spring:
  application:
    name: OSMReader
  data:
    mongodb:
      host: localhost
      port: 27017
      database: osm
      username: root
      password: example
      authentication-database: admin
  # input producer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      buffer-memory: 40960
      retries: 3
      batch-size: 4096
      enable-idempotence: true
      linger:
        ms: 1
      acks: all
    # input topic
    topic:
      name:
        for-input-topic: resolved_osm
      partitions:
        for-input-topic: 3
      replication-factor:
        for-input-topic: 1
#logging
#logging:
#  level:
#    org:
#      springframework:
#        data:
#          mongodb:
#            core: DEBUG
osm:
  file:
    path: src/main/resources/osm_data/map_center.osm