spring:
  application:
    name: OSMReader
  data:
    mongodb:
      host: localhost
      port: 27017
      database: osm
      username: root
      password: example
      authentication-database: admin
  kafka:
    producer:
      buffer-memory: 40960
      retries: 3
      batch-size: 4096
      linger:
        ms: 1
      acks: 1
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      name:
        for-input-topic: resolved_osm
      partitions:
        for-input-topic: 3
      replication-factor:
        for-input-topic: 1
    bootstrap-servers:
      - localhost:29092
#logging
#logging:
#  level:
#    org:
#      springframework:
#        data:
#          mongodb:
#            core: DEBUG
osm:
  file:
    path: src/main/resources/osm_data/map_center.osm


logging:
  level:
    root: INFO
  file:
    name: logs/app.log
    path: log